version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: internal/controller/http
        linters:
          - godot
      - linters:
          - staticcheck
        text: "QF1008"

formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
