# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: go-clean-architecture

builds:
  - id: app
    main: ./cmd/app
    binary: app
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

  - id: migrate
    main: ./cmd/migrate
    binary: migrate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

  - id: healthcheck
    main: ./cmd/healthcheck
    binary: healthcheck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: binaries
    ids:
      - app
      - migrate
      - healthcheck
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs?(\(.+\))?:'
      - '^test(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - '^ci(\(.+\))?:'
      - '^Merge pull request'
      - '^Merge branch'

release:
  prerelease: auto
  mode: replace
